config/routes.rb
Nomster::Application.routes.draw do
    
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, :only => :create
    resources :photos, :only => :create
  end
  resources :comments, :only => :destroy
  resources :users, :only => :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email
  
  # The hash key is what the user will see
  # The has value is what will be stored in the db
  RATINGS = {
    'one star'    => '1_star',
    'two stars'   => '2_stars',
    'three stars' => '3_stars',
    'four stars'  => '4_stars',
    'five stars'  => '5_stars'
  }
  
  def humanized_rating
    RATINGS.invert[self.rating]
  end
  
  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :place
  
  # When you include this field in a form, an uploader will be used
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :photos, :dependent => :destroy
  
  geocoded_by :address
  after_validation :geocode
  
  validates :name, :presence => true, :length => { :minimum => 4 }
  validates :address, :presence => true
  validates :description, :presence => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @place = Place.find( params[:place_id] )
    @place.comments.create( comment_params.merge(:user => current_user) )
    
    redirect_to place_path(@place)
  end
  
  def destroy
    comment = Comment.find(params[:id])
    
    if current_user == comment.user
      comment.destroy
    else
      return render :text => "Can't do that", :status => "forbidden"
    end
    
    redirect_to root_path
  end
  
  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @place = Place.find( params[:place_id] )
    
    if @place.user == current_user
      @place.photos.create(photo_params)
    end
    
    redirect_to place_path(@place)
    
  end
  
  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # Requires users to be authenticated for the action values of the only key
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  
  def index
    # Paginated db pull
    @places = Place.order("id ASC").paginate( :page => params[:page], :per_page => 2 )
    @testing = "TESTING"
  end
  
  def new
    @place = Place.new
  end
  
  def create
    @place = current_user.places.create(place_params)
    
    if @place.valid?
      redirect_to root_path
    else
      render :new, :status => :unprocessable_entity
    end
  end
  
  def show
    @place = Place.find(params[:id])
    
    @comment = Comment.new
    @my_comments = @place.comments.all
    @photo = Photo.new
  end
  
  def edit
    @place = Place.find(params[:id])
    
    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end
  end
  
  def update
    @place = Place.find(params[:id])
    
    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end
    
    @place.update_attributes(place_params)  
    
    if @place.valid?
      redirect_to root_path
    else
      render :edit, :status => :unprocessable_entity
    end

  end
  
  def destroy
    @place = Place.find(params[:id])
    
    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end
    
    @place.destroy
    
    redirect_to root_path
  end
  
  private
  
  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find( params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Nomster", root_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to new_place_path do %>
              <i class="glyphicon glyphicon-plus-sign"></i>
              New Place
            <% end %>
            
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  
  <%= yield %>
  
</body>
</html>

app/views/places/edit.html.erb
<div class="col-xs-10 col-xs-offset-1 booyah-box">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <br />
  <%= f.submit "Update", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/places/index.html.erb
<!-- Homepage Slider -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "slider3.jpg", :class => "img-responsive" %>
      <div class="carousel-caption">
        Looking for a fancy place to eat?
      </div>
    </div>
    <div class="item">
      <%= image_tag "slider4.jpg", :class => "img-responsive" %>
      <div class="carousel-caption">
        Or the best burger spot in town?
      </div>
    </div>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<% @places.each do |place| %>
  <div class="container-fluid">
    <div class="booyah-box col-xs-10 col-xs-offset-1">
      
      <% if place.photos.present? %>
        <div class="col-xs-12 col-sm-3 pull-right">
          <%= image_tag place.photos.first.picture, :class => "img-responsive pull-right" %>
        </div>
      <% end %>
      
      <h1><%= link_to place.name, place_path(place) %></h1>
      <i><%= place.address %></i><br /><br />
      <p><%= place.description %></p><br />
      
      <% if place.user.present? %>
        <small><%= place.user.email %></small>
      <% end %>
      
      <% if place.comments.present? %>
        <div class="col-xs-12">
          <blockquote>
            <% if place.comments.order("id ASC").last.humanized_rating.present? %>
              <b><%= place.comments.order("id ASC").last.humanized_rating %></b> - 
            <% end %>
            <%= place.comments.order("id ASC").last.message %>
            <small><%= place.comments.order("id ASC").last.user.email %></small>
          </blockquote>
        </div>
      <% end %>
      
    </div>
  </div>

<% end %>

<br class="clear"/>

<div class="container-fluid">
  <div class="col-xs-10 col-xs-offset-1 paginated-links-section">
    <%= will_paginate @places, :class => "paginated-link" %>
  </div>
</div>
<br class="clear" />
<br />

<div id="map">TESTING</div>
<br /><br />

<% if @places.present? %>
<script>
  function initMap() {
      var myLatLng = {lat: <%= @places.last.latitude %>, lng: <%= @places.last.longitude %>};
  
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });
      
      <% count = 0 %>
      <% @places.each do |place| %>            
        myLatLng = {lat: <%= place.latitude %>, lng: <%= place.longitude %>};
        marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: '<%=place.name%>'
        });
        <% count += 1 %>
      <% end %>
      
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap">
  </script>
<% end %>

app/views/places/new.html.erb
<div class="col-xs-10 col-xs-offset-1 booyah-box">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %><br />
    <%= f.input :description %><br />
    <%= f.input :address %>
    <br />
    <%= f.submit "Create", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/places/show.html.erb
<!-- Display Place Details -->
<div class="col-xs-10 col-xs-offset-1 booyah-box">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br /><br />
  <p><%= @place.description %></p>
  <p><%= "#{@place.latitude} and #{@place.longitude}" %></p>
  
  <% if @place.latitude.present? && @place.longitude.present? %>
  
  <script>
    $(document).ready(function() {
      $('a.fancybox').fancybox();
    });

    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
  
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
            
    }

  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap">
  </script>

  <div id="map"></div>
  
<% end %>  
  <br />
  
  <div class="pull-right">
    <% if current_user && (current_user == @place.user) %>
      <button class="btn btn-primary" data-toggle="modal" data-target="#myPhotoModal">
        Add Photo
      </button>  
      <%= link_to 'Edit', edit_place_path(@place), :class => 'btn btn-primary' %>
      <%= link_to 'Destroy', place_path(@place), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this?'}, :class => 'btn btn-danger' %>
    <% end %>
  </div>
</div>

<div class="clear"></div>

<!-- Comments header -->
<div class="col-xs-10 col-xs-offset-1">
  <h2 class="pull-left">Comments</h2>
  <!-- Button trigger modal -->
  <button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">
    Add a comment
  </button>
</div>  

<div class="clear"></div>

<!-- List comments for the current place -->
<% if @place.comments.present? %>
  <% @place.comments.each do |c| %>
    <div class="col-xs-10 col-sm-6">
      <blockquote>
        <% if c.humanized_rating.present? %>
          <b><%= c.humanized_rating %></b> - 
        <% end %>
        <%= c.message %>
        <small><%= c.user.email %></small>
      </blockquote>
    </div>
  <% end %>
<% else %>
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-1">
    <blockquote>
      <span>No Comments</span>
    </blockquote>
  </div>
<% end %>
<br class="clear" />
<br />

<div class="clear"></div>

<!-- Display photos attached to the current place -->
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 photo_row booyah-box">
  <h2>Photos</h2><br />
  <% @place.photos.each do |image| %>
    <div class="col-xs-12 col-sm-3 photo">
      
      <%= link_to image_tag(image.picture, :class => "img-responsive"), "#{image.picture}", :class => "fancybox" %>
      <br />
      <%= image.caption %>
    </div>
  <% end %>
</div>
<br class="clear" />
  
<!-- Comment Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <%= simple_form_for @comment, :url => place_comments_path(@place) do |c| %>
        <div class="modal-body">        
          <%= c.input :message %>
          <%= c.input :rating, :as => :select, :collection => Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= c.submit "Add a Comment", :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Photo Modal -->
<div class="modal fade" id="myPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myPhotoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myPhotoModalLabel">Upload a photo</h4>
      </div>
      <%= simple_form_for @photo, :url => place_photos_path(@place) do |p| %>
        <div class="modal-body">        
          <%= p.input :picture %>
          <br />
          <%= p.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= p.submit "Upload", :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="col-xs-4">
    <%= image_tag "user5.png", :class => "img-responsive center-block" %>
    <h2 class="text-center"><%= @user.email %></h2>
  </div>
  
  <div class="col-xs-8 member-stats">
    <div class="pull-right">
      <h3>Member Since: <%= @user.created_at.strftime('%B %d, %Y') %></h3>
      <br /><br />
      <h4 class="text-center"><%= @user.comments.count %> total comments</h4>
      <br />
      <h4 class="text-center"><%= @user.comments.where(:rating => '5_stars').count %> total 5 star reviews</h4>
    </div>
  </div>
  <div class="clear"></div>
</div>

<br /><br />
<h1 class="text-center">My Comments</h1>
<br /><br />

<% @user.comments.each do |comment| %>
  <div class="col-xs-8 col-xs-offset-1">
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> - 
      <% end %>
      <%= comment.message %>
      <% if comment.place.present? %>
        <span class="pull-right place-link"> <%= link_to ">> #{comment.place.name}", place_path(comment.place) %></span>
      <% else %>
        <span class="pull-right place-link"><h3>"Sorry, this place has been removed"</h3></span>
      <% end %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>

<div class="clear"></div>
<br /><br />
<h2 class="text-center">My Places</h2>
<br /><br />
<% @user.places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <% if place.photos.present? %>
      <div class="col-xs-12 col-sm-3 pull-right">
        <%= image_tag place.photos.first.picture, :class => "img-responsive pull-right" %>
      </div>
    <% end %>
    
    <h1><%= link_to place.name, place_path(place) %></h1>
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> - 
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
      
    </div>
<% end %>